### ISSUE TITLE
Login to dashboard failed

### ISSUE THREAD

**Issue by ssl42** [navi1995/Movie-Night-Discord-Bot#36]
I wasn't able to log into the dashboard when I tried it said this "MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/home/moviqnga/nodevenv/DashboardTestAPI/12/lib/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)"
After I reloaded it said this: "TokenError: Invalid "code" in request.
    at Strategy.OAuth2Strategy.parseErrorResponse (/home/moviqnga/nodevenv/DashboardTestAPI/12/lib/node_modules/passport-oauth2/lib/strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (/home/moviqnga/nodevenv/DashboardTestAPI/12/lib/node_modules/passport-oauth2/lib/strategy.js:405:16)
    at /home/moviqnga/nodevenv/DashboardTestAPI/12/lib/node_modules/passport-oauth2/lib/strategy.js:175:45
    at /home/moviqnga/nodevenv/DashboardTestAPI/12/lib/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/home/moviqnga/nodevenv/DashboardTestAPI/12/lib/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/home/moviqnga/nodevenv/DashboardTestAPI/12/lib/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)"

Help I don't know what to do the bot is already authorized to my account

**Comment by navi1995** [comment]
HI @ssl42 could you please try again? The websites API server was down I've just restarted it.

**Comment by ssl42** [comment]
Works
